"""initial schema

Revision ID: 4aec0811a363
Revises:
Create Date: 2026-08-01 17:40:12.527320

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4aec0811a363"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=True),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_occurred_at"), ["occurred_at"], unique=False)

    op.create_table(
        "evidence",
        sa.Column("evidence_id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("media_type", sa.String(length=64), nullable=False),
        sa.Column("relative_path", sa.String(length=512), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("evidence_id"),
    )
    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_evidence_session_id"), ["session_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_evidence_sha256"), ["sha256"], unique=False)

    op.create_table(
        "lifecycle_signals",
        sa.Column("signal_id", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=512), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("device_id", sa.String(length=128), nullable=False),
        sa.Column("media_epoch_id", sa.String(length=64), nullable=True),
        sa.Column("object_id", sa.String(length=64), nullable=True),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("signal_id"),
    )
    with op.batch_alter_table("lifecycle_signals", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lifecycle_signals_idempotency_key"), ["idempotency_key"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_lifecycle_signals_session_id"), ["session_id"], unique=False
        )

    op.create_table(
        "object_states",
        sa.Column("object_id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=False),
        sa.Column("current_status", sa.String(length=32), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("state", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("object_id"),
    )
    with op.batch_alter_table("object_states", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_object_states_current_status"), ["current_status"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_object_states_label"), ["label"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_object_states_session_id"), ["session_id"], unique=False
        )

    op.create_table(
        "observations",
        sa.Column("observation_id", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=512), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("device_id", sa.String(length=128), nullable=False),
        sa.Column("media_epoch_id", sa.String(length=64), nullable=True),
        sa.Column("object_id", sa.String(length=64), nullable=True),
        sa.Column("label", sa.String(length=128), nullable=False),
        sa.Column("track_id", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_confidence", sa.Float(), nullable=False),
        sa.Column("identity_confidence", sa.Float(), nullable=False),
        sa.Column("promoted", sa.Boolean(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("observation_id"),
    )
    with op.batch_alter_table("observations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_observations_idempotency_key"), ["idempotency_key"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_observations_object_id"), ["object_id"], unique=False)
        batch_op.create_index(
            "ix_observations_object_time", ["object_id", "occurred_at"], unique=False
        )
        batch_op.create_index("ix_observations_session", ["session_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_observations_session_id"), ["session_id"], unique=False
        )

    op.create_table(
        "sessions",
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("device_id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("session_id"),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sessions_device_id"), ["device_id"], unique=False)

    op.create_table(
        "object_identities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("media_epoch_id", sa.String(length=64), nullable=True),
        sa.Column("track_id", sa.String(length=128), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=False),
        sa.Column("object_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "session_id", "media_epoch_id", "track_id", "label", name="uq_identity_scope"
        ),
    )
    with op.batch_alter_table("object_identities", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_object_identities_label"), ["label"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_object_identities_object_id"), ["object_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("object_identities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_object_identities_object_id"))
        batch_op.drop_index(batch_op.f("ix_object_identities_label"))

    op.drop_table("object_identities")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_device_id"))

    op.drop_table("sessions")
    with op.batch_alter_table("observations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_observations_session_id"))
        batch_op.drop_index("ix_observations_session")
        batch_op.drop_index("ix_observations_object_time")
        batch_op.drop_index(batch_op.f("ix_observations_object_id"))
        batch_op.drop_index(batch_op.f("ix_observations_idempotency_key"))

    op.drop_table("observations")
    with op.batch_alter_table("object_states", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_object_states_session_id"))
        batch_op.drop_index(batch_op.f("ix_object_states_label"))
        batch_op.drop_index(batch_op.f("ix_object_states_current_status"))

    op.drop_table("object_states")
    with op.batch_alter_table("lifecycle_signals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lifecycle_signals_session_id"))
        batch_op.drop_index(batch_op.f("ix_lifecycle_signals_idempotency_key"))

    op.drop_table("lifecycle_signals")
    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evidence_sha256"))
        batch_op.drop_index(batch_op.f("ix_evidence_session_id"))

    op.drop_table("evidence")
    with op.batch_alter_table("audit", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_audit_action"))

    op.drop_table("audit")
    # ### end Alembic commands ###
