#!/usr/bin/env bash
#
# LiveKit credentials, generated once and shared by every script that needs
# them.
#
# The server and the gateway must hold the *same* key/secret pair. A mismatch
# does not fail where it happened: the gateway mints a token the server then
# refuses, and the browser reports a join failure that reads like a network
# problem. So the pair is generated once, written to a gitignored .env at the
# repository root -- which is also where Docker Compose looks -- and reused
# forever after.
#
# Sourced, never executed. Callers get `ensure_livekit_credentials`, which
# exports VMA_LIVEKIT_API_KEY and VMA_LIVEKIT_API_SECRET.

# Prefers openssl, which is on every developer machine here, but does not
# require it: uv can supply its own Python, so a machine can have neither
# openssl nor a system python3 -- the caller checks for python3 separately.
random_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 24
  else
    python3 -c "import secrets; print(secrets.token_hex(24))"
  fi
}

# ensure_livekit_credentials <env_file>
#
# Loads an existing pair, or generates and persists one. Exports both.
ensure_livekit_credentials() {
  local env_file="$1"

  if [[ -f "$env_file" ]]; then
    set -a
    # shellcheck disable=SC1090  # the path is the caller's, by design
    source "$env_file"
    set +a
  fi

  if [[ -z "${VMA_LIVEKIT_API_KEY:-}" || -z "${VMA_LIVEKIT_API_SECRET:-}" ]]; then
    VMA_LIVEKIT_API_KEY="vma-dev-$(whoami)"
    VMA_LIVEKIT_API_SECRET="$(random_secret)"
    umask 077
    cat > "$env_file" <<EOF
# Generated by scripts/lib/livekit_env.sh. Gitignored -- never commit this file.
# Both the LiveKit server and the gateway read these, so they cannot drift.
VMA_LIVEKIT_API_KEY=$VMA_LIVEKIT_API_KEY
VMA_LIVEKIT_API_SECRET=$VMA_LIVEKIT_API_SECRET
EOF
    printf '   %s\n' "generated new credentials in $env_file (gitignored)"
  else
    printf '   %s\n' "using existing credentials from $env_file"
  fi

  export VMA_LIVEKIT_API_KEY VMA_LIVEKIT_API_SECRET
}
