#Requires -Version 5.1
<#
.SYNOPSIS
Bring up everything needed to publish a real camera into the pipeline.

.DESCRIPTION
The Windows twin of dev_up.sh. Replaces the three-step sequence -- generate
credentials, start LiveKit, start the gateway -- with one command. The three
steps are not hard, but the credentials have to match between the server and
the gateway, and a mismatch fails in a way that looks like a network problem
rather than a config one. This generates them once, persists them to a
gitignored .env at the repository root, and reuses them forever after.

Ctrl-C stops whatever this script started.

.PARAMETER Scripted
Skip LiveKit entirely and run on synthetic video.

.PARAMETER StrictGuard
Reject any frame that is not the configured size, instead of latching the
first size each epoch produces.

.PARAMETER Port
Serve the gateway somewhere other than 8080.

.PARAMETER KeepLiveKit
Leave the LiveKit server running when the gateway stops.

.EXAMPLE
.\scripts\dev_up.ps1

.EXAMPLE
.\scripts\dev_up.ps1 -Scripted
#>
[CmdletBinding()]
param(
    [switch]$Scripted,
    [switch]$StrictGuard,
    [switch]$KeepLiveKit,
    [int]$Port = 8080
)

$ErrorActionPreference = "Stop"

$ServiceDir = Split-Path -Parent $PSScriptRoot
$RepoRoot = Split-Path -Parent (Split-Path -Parent $ServiceDir)
$EnvFile = Join-Path $RepoRoot ".env"
$ComposeFile = Join-Path $RepoRoot "compose.dev.yaml"
$script:StartedLiveKit = $false

function Write-Section($text) { Write-Host "`n== $text" -ForegroundColor Cyan }
function Write-Info($text) { Write-Host "   $text" }
function Fail($text) { Write-Host "FAIL $text" -ForegroundColor Red; exit 1 }

function Test-PortInUse([int]$number) {
    # A real listener check: anything on this port makes uvicorn fail to bind,
    # and probing a health endpoint would only notice another gateway.
    $client = New-Object System.Net.Sockets.TcpClient
    try {
        $result = $client.BeginConnect("127.0.0.1", $number, $null, $null)
        if ($result.AsyncWaitHandle.WaitOne(400)) {
            $client.EndConnect($result)
            return $true
        }
        return $false
    } catch {
        return $false
    } finally {
        $client.Close()
    }
}

function Test-LiveKitUp {
    try {
        Invoke-WebRequest -Uri "http://127.0.0.1:7880" -UseBasicParsing -TimeoutSec 2 | Out-Null
        return $true
    } catch {
        # LiveKit answers non-2xx on /, which still proves it is listening.
        return $_.Exception.Response -ne $null
    }
}

try {
    if (-not (Get-Command uv -ErrorAction SilentlyContinue)) {
        Fail "uv is not installed -- see https://docs.astral.sh/uv/"
    }
    if (-not (Get-Command python -ErrorAction SilentlyContinue)) {
        Fail "python is not on PATH"
    }

    # --- Credentials --------------------------------------------------------

    if (Test-Path $EnvFile) {
        Get-Content $EnvFile | ForEach-Object {
            if ($_ -match '^\s*([A-Z_][A-Z0-9_]*)\s*=\s*(.*)$') {
                Set-Item -Path "Env:$($Matches[1])" -Value $Matches[2]
            }
        }
    }

    if (-not $env:VMA_LIVEKIT_API_KEY -or -not $env:VMA_LIVEKIT_API_SECRET) {
        Write-Section "Generating LiveKit credentials"
        $bytes = New-Object byte[] 24
        [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
        $env:VMA_LIVEKIT_API_KEY = "vma-dev-$env:USERNAME"
        $env:VMA_LIVEKIT_API_SECRET = -join ($bytes | ForEach-Object { $_.ToString("x2") })
        @(
            "# Generated by scripts/dev_up.ps1. Gitignored -- never commit this file.",
            "# Both the LiveKit server and the gateway read these, so they cannot drift.",
            "VMA_LIVEKIT_API_KEY=$env:VMA_LIVEKIT_API_KEY",
            "VMA_LIVEKIT_API_SECRET=$env:VMA_LIVEKIT_API_SECRET"
        ) | Set-Content -Path $EnvFile -Encoding ascii
        Write-Info "written to .env (gitignored)"
    } else {
        Write-Info "using existing credentials from .env"
    }

    # --- Dependencies -------------------------------------------------------

    Write-Section "Syncing dependencies"
    Set-Location $ServiceDir
    # --all-groups, not a bare sync: without it uv prunes the optional groups
    # and silently uninstalls `av`, breaking `virtual-glasses --file`.
    uv sync --frozen --all-groups | Out-Null
    if ($LASTEXITCODE -ne 0) { Fail "uv sync" }

    # Verify rather than trust. A .venv left over from an earlier checkout can
    # be missing the project's editable link while `uv sync --frozen` still
    # reports "Audited N packages" -- it compares against the lock, not against
    # what is actually importable. uvicorn then dies with a bare
    # ModuleNotFoundError that reads like a broken repository.
    uv run --no-sync python -c "import media_gateway" 2>&1 | Out-Null
    if ($LASTEXITCODE -ne 0) {
        Write-Info "environment is stale; reinstalling"
        uv sync --frozen --all-groups --reinstall | Out-Null
        if ($LASTEXITCODE -ne 0) { Fail "uv sync --reinstall" }
        uv run --no-sync python -c "import media_gateway" 2>&1 | Out-Null
        if ($LASTEXITCODE -ne 0) {
            Fail "media_gateway is still not importable -- remove .venv and re-run"
        }
    }
    Write-Info "ready"

    # --- LiveKit ------------------------------------------------------------

    if ($Scripted) {
        Write-Section "Scripted mode -- no LiveKit, synthetic video only"
        $mediaSource = "scripted"
    } else {
        $mediaSource = "livekit"
        if (Test-LiveKitUp) {
            Write-Section "LiveKit is already running"
        } else {
            if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
                Fail "docker is not installed -- use -Scripted, or see tools/dev-livekit/"
            }
            # Order matters. `docker compose version` also fails when the
            # daemon is unreachable, so checking the plugin first would report
            # a missing plugin to someone who has simply not started Docker
            # Desktop.
            docker info 2>&1 | Out-Null
            if ($LASTEXITCODE -ne 0) {
                Fail "the docker daemon is not running -- start Docker Desktop, or use -Scripted"
            }
            docker compose version 2>&1 | Out-Null
            if ($LASTEXITCODE -ne 0) {
                Fail "the docker compose plugin is missing (v1 'docker-compose' will not do)"
            }
            Write-Section "Starting LiveKit"
            docker compose -f $ComposeFile up -d livekit | Out-Null
            if ($LASTEXITCODE -ne 0) {
                Fail "could not start LiveKit -- check 'docker compose -f compose.dev.yaml logs livekit'"
            }
            $script:StartedLiveKit = $true
            $ready = $false
            foreach ($_ in 1..40) {
                if (Test-LiveKitUp) { $ready = $true; break }
                Start-Sleep -Milliseconds 500
            }
            if (-not $ready) { Fail "LiveKit did not become reachable on 127.0.0.1:7880" }
        }

        # Exposure is a privacy requirement: docs/07 asks for listeners to be
        # verified rather than inferred from the WebSocket URL.
        Write-Section "Checking what LiveKit is listening on"
        python (Join-Path $RepoRoot "tools\dev-livekit\check_listeners.py")
        if ($LASTEXITCODE -ne 0) {
            Fail "LiveKit is reachable beyond loopback -- see docs/07-Privacy-and-Security.md"
        }
    }

    # --- Gateway ------------------------------------------------------------

    if (Test-PortInUse $Port) {
        Fail "something is already listening on port $Port -- stop it, or pass -Port"
    }

    Write-Section "Starting the gateway"
    $guard = if ($StrictGuard) { "strict" } else { "first_frame_wins" }
    Write-Info "source: $mediaSource   guard: $guard   port: $Port"

    $env:VMA_ENVIRONMENT = "dev"
    $env:VMA_MEDIA_SOURCE = $mediaSource
    $env:VMA_DIMENSION_GUARD_MODE = $guard

    $gateway = Start-Process -FilePath "uv" `
        -ArgumentList @("run", "uvicorn", "media_gateway.main:app",
                        "--port", "$Port", "--log-level", "warning") `
        -NoNewWindow -PassThru

    $ready = $false
    foreach ($_ in 1..60) {
        if ($gateway.HasExited) { Fail "the gateway exited during startup" }
        try {
            Invoke-WebRequest -Uri "http://127.0.0.1:$Port/health/ready" `
                -UseBasicParsing -TimeoutSec 2 | Out-Null
            $ready = $true
            break
        } catch { Start-Sleep -Milliseconds 500 }
    }
    if (-not $ready) { Fail "the gateway did not become ready" }

    Write-Host "`n READY " -ForegroundColor Green
    Write-Host ""
    if (-not $Scripted) {
        # This script starts the gateway alone, and publishing a camera needs a
        # browser page that no longer ships with it.
        Write-Host "  Publish a camera   cd $RepoRoot\apps\console; npm run dev" -ForegroundColor White
        Write-Host "                     then http://localhost:5173"
        Write-Host "                     Or .\scripts\dev_stack.sh for the whole stack."
        Write-Host ""
    }
    Write-Host "  Watch the frames   cd $ServiceDir"
    Write-Host "                     uv run python -m visual_memory_media_contract.tap ``"
    Write-Host "                       ws://127.0.0.1:$Port/v1/stream/video"
    Write-Host ""
    Write-Host "  Gateway state      curl http://localhost:$Port/v1/status"
    Write-Host ""
    Write-Host "  Ctrl-C to stop."
    Write-Host ""

    $gateway.WaitForExit()
} finally {
    if ($script:StartedLiveKit -and -not $KeepLiveKit) {
        Write-Section "Stopping the LiveKit server this script started"
        docker compose -f $ComposeFile down 2>&1 | Out-Null
    }
}
